CREATE TABLE [dbo].[SubjectDrugHistory] (
[Id] INT IDENTITY(1,1) NOT NULL,
    [SubjectDrugId]      INT             NOT NULL,
    [SubjectId]          INT             NOT NULL,
    [DrugId]             INT             NOT NULL,
    [AppointmentId]      INT             NOT NULL,
    [StartDate]          DATETIME        NULL,
    [EndDate]            DATETIME        NULL,
    [MultipleTrialsId]   INT             NULL,
    [DurationUsed]       INT             NULL,
    [ReasonStoppedId]    INT             NOT NULL,
    [ReasonTypeId]       INT             NOT NULL,
    [TreatmentInducedId] INT             NOT NULL,
    [DosageFrequencyId]  INT             NOT NULL,
    [IsCurrent]          BIT             CONSTRAINT [DF_SubjectDrugHistory_IsCurrent] DEFAULT ((0)) NOT NULL,
    [IsChanged]          BIT             CONSTRAINT [DF_SubjectDrugHistory_IsChanged] DEFAULT ((0)) NOT NULL,
    [IsStopped]          BIT             CONSTRAINT [DF_SubjectDrugHistory_IsStopped] DEFAULT ((0)) NOT NULL,
    [IsBeforeStudy]      BIT             CONSTRAINT [DF_SubjectDrugHistory_IsBeforeStudy] DEFAULT ((0)) NOT NULL,
    [Dosage]             NVARCHAR (200)  NULL,
    [DosageType]         NVARCHAR (200)  NULL,
    [Notes]              NVARCHAR (1000) NULL,
    [MdNotes]            NVARCHAR (MAX)  NULL,
    [Comments]           NVARCHAR (MAX)  NULL,
    [Status]             INT             CONSTRAINT [DF_SubjectDrugHistory_Status] DEFAULT ((1)) NOT NULL,
    [CreatedOn]          DATETIME        CONSTRAINT [DF_SubjectDrugHistory_CreatedOn] DEFAULT (GETUTCDATE()) NOT NULL,
    [UpdatedOn]          DATETIME        NULL,
    [SavedOn]            DATETIME2 (7)   CONSTRAINT [DF_SubjectDrugHistory_SavedOn] DEFAULT (GETUTCDATE()) NOT NULL
);

