//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class AnswerChildQuestion
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    	public int AnswerId { get; set; }
    	
    	public int QuestionId { get; set; }
    	
    	public Nullable<bool> IsActive { get; set; }
    	
    	public virtual Answer Answer { get; set; }
    	
    	public virtual Question Question { get; set; }
    }
    
}
