//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class AppointmentForm
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppointmentForm()
        {		
    		this.FormAnswers = new HashSet<FormAnswer>();
        }
    
    	
    		
    	public int FormId { get; set; }
    	
    	public int AppointmentId { get; set; }
    	
    	public int FormStatusTypeId { get; set; }
    	
    	public string Notes { get; set; }
    	
    	public string Comments { get; set; }
    	
    	public int TotalScore { get; set; }
    	
    	public int Status { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public Nullable<System.DateTime> CreatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public virtual Appointment Appointment { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<FormAnswer> FormAnswers { get; set; }
    	
    	public virtual Form Form { get; set; }
    }
    
}
