//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class AppUser
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppUser()
        {		
    		this.UserSettings = new HashSet<UserSetting>();
        }
    
    	
    		
    	public System.Guid MembershipUserId { get; set; }
    	
    	public int SiteId { get; set; }
    	
    	public System.Guid RoleId { get; set; }
    	
    	public int ContactId { get; set; }
    	
    	public string Title { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public string Comments { get; set; }
    	
    	public int Status { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public Nullable<System.DateTime> CreatedOn { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public virtual Contact Contact { get; set; }
    	
    	public virtual Role Role { get; set; }
    	
    	public virtual Site Site { get; set; }
    	
    	public virtual User User { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<UserSetting> UserSettings { get; set; }
    }
    
}
