//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class Drug
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drug()
        {		
    		this.SubjectDrugs = new HashSet<SubjectDrug>();
        }
    
    	
    		
    	public int DrugClassId { get; set; }
    	
    	public Nullable<int> DrugTypeId { get; set; }
    	
    	public int StudyId { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string Directions { get; set; }
    	
    	public int Status { get; set; }
    	
    	public string Description { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public Nullable<System.DateTime> CreatedOn { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public virtual DrugClass DrugClass { get; set; }
    	
    	public virtual Study Study { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<SubjectDrug> SubjectDrugs { get; set; }
    }
    
}
