//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class File
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {		
    		this.Studies = new HashSet<Study>();
    		
    		this.Subjects = new HashSet<Subject>();
        }
    
    	
    		
    	public System.Guid FileGuid { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string FileType { get; set; }
    	
    	public byte[] FielContent { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public System.DateTime CreatedOn { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<Study> Studies { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<Subject> Subjects { get; set; }
    }
    
}
