//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class FormQuestionAnswerImport
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    		
    	public int FormId { get; set; }
    	
    	public string FormName { get; set; }
    	
    	public string title { get; set; }
    	
    	public string Description { get; set; }
    	
    	public int FormType { get; set; }
    	
    	public int QuestionId { get; set; }
    	
    	public string QuestionText { get; set; }
    	
    	public int QuestionTypeId { get; set; }
    	
    	public int AnswerId { get; set; }
    	
    	public string AnswerText { get; set; }
    }
    
}
