//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class Form
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Form()
        {		
    		this.AppointmentForms = new HashSet<AppointmentForm>();
    		
    		this.FormVerifications = new HashSet<FormVerification>();
    		
    		this.FormVisibilityByVisitForSubjects = new HashSet<FormVisibilityByVisitForSubject>();
    		
    		this.VisitForms = new HashSet<VisitForm>();
    		
    		this.Questions = new HashSet<Question>();
    		
    		this.LibraryQuestions = new HashSet<LibraryQuestion>();
        }
    
    	
    		
    	public int StudyId { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string Code { get; set; }
    	
    	public int FormTypeId { get; set; }
    	
    	public string Title { get; set; }
    	
    	public string Directions { get; set; }
    	
    	public string Header { get; set; }
    	
    	public string Trailer { get; set; }
    	
    	public bool IsFilledBySubject { get; set; }
    	
    	public bool ShowTotalScore { get; set; }
    	
    	public int LayoutTypeId { get; set; }
    	
    	public Nullable<bool> IsDoubleChecked { get; set; }
    	
    	public string Description { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public int Status { get; set; }
    	
    	public System.DateTime CreatedOn { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public bool NotifyOnChange { get; set; }
    	
    	public bool NotifyOnCompletion { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<AppointmentForm> AppointmentForms { get; set; }
    	
    	public virtual Study Study { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<FormVerification> FormVerifications { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<FormVisibilityByVisitForSubject> FormVisibilityByVisitForSubjects { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<VisitForm> VisitForms { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<Question> Questions { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<LibraryQuestion> LibraryQuestions { get; set; }
    }
    
}
