//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class FormInProcess
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    		
    	public int FormId { get; set; }
    	
    	public int SubjectId { get; set; }
    	
    	public int AppUserId { get; set; }
    	
    	public bool IsLocked { get; set; }
    	
    	public System.DateTime OpenendOn { get; set; }
    	
    	public Nullable<System.DateTime> ReleasedOn { get; set; }
    	
    	public int MaxLockTimeMin { get; set; }
    	
    	public int UnlockedByAppUserId { get; set; }
    }
    
}
