//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class MessageQueue
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    		
    	public int TemplateId { get; set; }
    	
    	public int PriorityId { get; set; }
    	
    	public string Data { get; set; }
    	
    	public int RecipientId { get; set; }
    	
    	public int SenderId { get; set; }
    	
    	public int StatusId { get; set; }
    	
    	public System.DateTime QueuedOn { get; set; }
    	
    	public Nullable<System.DateTime> LastProcessedOn { get; set; }
    	
    	public int TriesCount { get; set; }
    	
    	public string Description { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public int Status { get; set; }
    	
    	public System.DateTime CreatedOn { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public virtual MessageTemplate MessageTemplate { get; set; }
    }
    
}
