//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class Profile
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    		
    	public System.Guid UserId { get; set; }
    	
    	public string PropertyNames { get; set; }
    	
    	public string PropertyValueStrings { get; set; }
    	
    	public byte[] PropertyValueBinary { get; set; }
    	
    	public System.DateTime LastUpdatedDate { get; set; }
    	
    	public virtual User User { get; set; }
    }
    
}
