//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class Subject
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {		
    		this.SubjectDrugs = new HashSet<SubjectDrug>();
    		
    		this.Files = new HashSet<File>();
        }
    
    	
    		
    	public int SiteId { get; set; }
    	
    	public int ContactId { get; set; }
    	
    	public int StudyId { get; set; }
    	
    	public string Nickname { get; set; }
    	
    	public string FamilyId { get; set; }
    	
    	public string Notes { get; set; }
    	
    	public string NIMHID { get; set; }
    	
    	public int GenderTypeId { get; set; }
    	
    	public int YearBorn { get; set; }
    	
    	public string DateOfBirth { get; set; }
    	
    	public string SSN { get; set; }
    	
    	public byte[] SSNEnc { get; set; }
    	
    	public byte[] FirstNameEnc { get; set; }
    	
    	public byte[] LastNameEnc { get; set; }
    	
    	public byte[] DateOfBirthEnc { get; set; }
    	
    	public string Directions { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public int Status { get; set; }
    	
    	public System.DateTime CreatedOn { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public virtual Contact Contact { get; set; }
    	
    	public virtual Site Site { get; set; }
    	
    	public virtual Study Study { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<SubjectDrug> SubjectDrugs { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<File> Files { get; set; }
    }
    
}
