//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class VisitStepVisitSequence
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    	
    	public int VisitStepId { get; set; }
    	
    	public int VisitId { get; set; }
    	
    	public int DaysFromBase { get; set; }
    	
    	public bool IsActive { get; set; }
    	
    	public int Deviation { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public bool IsTermination { get; set; }
    	
    	public virtual Visit Visit { get; set; }
    	
    	public virtual VisitStep VisitStep { get; set; }
    }
    
}
