//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
//	
//    Modified for BRRO project
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Tateeda.Clires.Core.Data.EF
{
    public partial class Visit
    {
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {		
    		this.Appointments = new HashSet<Appointment>();
    		
    		this.FormVisibilityByVisitForSubjects = new HashSet<FormVisibilityByVisitForSubject>();
    		
    		this.ScheduleSubjectVisits = new HashSet<ScheduleSubjectVisit>();
    		
    		this.ChildVisit = new HashSet<Visit>();
    		
    		this.VisitForms = new HashSet<VisitForm>();
    		
    		this.VisitStepVisitSequences = new HashSet<VisitStepVisitSequence>();
    		
    		this.VisitSteps = new HashSet<VisitStep>();
        }
    
    	
    		
    	public int VisitTypeId { get; set; }
    	
    	public int ArmId { get; set; }
    	
    	public string Name { get; set; }
    	
    	public string Code { get; set; }
    	
    	public string Directions { get; set; }
    	
    	public Nullable<int> ParentVisitId { get; set; }
    	
    	public bool IsBaseVisit { get; set; }
    	
    	public bool CanRepeat { get; set; }
    	
    	public bool CanMove { get; set; }
    	
    	public bool HasChild { get; set; }
    	
    	public int SortOrder { get; set; }
    	
    	public int Status { get; set; }
    	
    	public System.DateTime CreatedOn { get; set; }
    	
    	public Nullable<System.DateTime> UpdatedOn { get; set; }
    	
    	public string CreatedBy { get; set; }
    	
    	public string UpdatedBy { get; set; }
    	
    	public bool IsActive { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<Appointment> Appointments { get; set; }
    	
    	public virtual Arm Arm { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<FormVisibilityByVisitForSubject> FormVisibilityByVisitForSubjects { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<ScheduleSubjectVisit> ScheduleSubjectVisits { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<Visit> ChildVisit { get; set; }
    	
    	public virtual Visit ParentVisit { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<VisitForm> VisitForms { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<VisitStepVisitSequence> VisitStepVisitSequences { get; set; }
    	[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    		
    	public virtual ICollection<VisitStep> VisitSteps { get; set; }
    }
    
}
